<?php

namespace Tests\Framework\HTTP;

use Framework\HTTP\Request;
use PHPUnit\Framework\TestCase;

class RequestTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $_GET = [];
        $_POST = [];
    }
}